version: "3.8"

networks:
  api-backend:

services:

  database:
    container_name: ${POSTGRES_CONTAINER}
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  cache:
    container_name: ${REDIS_CONTAINER}
    image: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  backend:
    build:
      context: ./.docker/backend
    tty: true
    volumes:
      - .:/workspaces:cached
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - database
      - cache


