version: "3.8"

networks:
  api-backend:

services:

  database:
    image: postgres
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: backend
    ports:
      - 5432:5432

  cache:
    image: redis
    ports:
      - 6379:6379

  backend:
    build:
      context: ./.docker/backend
    tty: true
    volumes:
      - .:/workspaces:cached
    ports:
      - 8080:8080
    depends_on:
      - database
      - cache


