swagger:
    server-url: http://localhost:8080
spring:
    cache:
        type: redis
    data:
        redis:
            host: ${REDIS_HOST}
    devtools:
        restart:
            enabled: true
    datasource:
        url: jdbc:postgresql://localhost:5432/backend
        username: db
        password: db
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
springdoc:
    api-docs:
        path: /api-docs
viacep-api:
    baseUrl: https://viacep.com.br/ws
