spring:
    datasource:
        url: jdbc:h2:mem:testdb
        username: db
        password: db
        driverClassName: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect

springdoc:
    api-docs:
        path: /api-docs
    
