swagger:
    config:
        url: http://localhost:8080

spring:
    cache:
        type: redis

    data:
        redis:
            host: cache
            port: 6379

    devtools:
        restart:
            enabled: true

    datasource:
        url: jdbc:postgresql://db:5432/backend
        username: db
        password: db
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
    api-docs:
        path: /api-docs

viacep-api:
    baseUrl: https://viacep.com.br/ws